import { PlayerPosition, PlayingPosition, Player } from '../models/players.model';


export const PLAYER: Player = {
	id: 1,
	clubId: 1001,
	countryId: 1,
	name: 'Massimo',
	surname: 'Truzzi',
	shirtNumber: 8,
	dateOfBirth: new Date(),
	age: [21, 88],
	salary: 250000,
	contractLength: 3,
	position: PlayerPosition.CM,
	weight: 88,
	height: 185,
	injured: false,
	retired: false,
	avatar: 2,
	seasonGoals: 3,
	careerGoals: 16,
	playingPosition: PlayingPosition.Position6,
	fitness: 75,
	attacking: 12,
	defending: 8,
	goalkeeping: 3,
	passing: 8,
	shooting: 3,
	heading: 3,
	quickness: 7,
	strength: 7
};

export const PLAYERS: Player[] = [
	PLAYER, {
		id: 2,
		clubId: 1001,
		countryId: 1,
		name: 'Angelo',
		surname: 'Galesi',
		shirtNumber: 10,
		dateOfBirth: new Date(),
		age: [23, 25],
		salary: 250000,
		contractLength: 3,
		position: PlayerPosition.ST,
		weight: 88,
		height: 185,
		injured: false,
		retired: false,
		avatar: 2,
		seasonGoals: 3,
		careerGoals: 16,
		playingPosition: PlayingPosition.Position11,
		fitness: 75,
		attacking: 12,
		defending: 3,
		goalkeeping: 1,
		passing: 8,
		shooting: 8,
		heading: 8,
		quickness: 7,
		strength: 7
	}];
